### PR TITLE
Fix Issue #319 - Rename prod profile to preview

### LINKED ISSUE #319: Rename "prod" profile to "preview"
### Description

Calling "prod" profile might confuse users into thinking that the operator can deliver an immutable image ready for production use cases. While this can be true in simplistic scenarios, real use cases require much more than the simple embedded build platform that we currently ship with the operator.

On Kubernetes we rely on Kaniko, on OpenShift on a simple `BuildConfig` object. This setup is more for a "preview" or staging use cases where user wants a glimpse of what it will look like a lighter image and immutable workflow on their topology.

Real use cases must rely on external build tooling. An example can be seen in this repo: https://github.com/flows-examples/gitops

This proposal is to change the `prod` profile naming and internal modules to `preview`. The profile capable to analyze and deploy an external built image we will call internally to `gitops` and it's activated as long as there's a `.spec.podTemplate.flowContainer.image` valid attribute set.

### Implementation ideas

Simply renaming and refactoring. No new features to add. Also, the guides must be updated accordingly.

### PR DESCRIPTION
**Pull request by ricardozanini**
**Description of the change:**
Fixes #319 

**Motivation for the change:**

**Checklist**

- [ ] Add or Modify a unit test for your change
- [ ] Have you verified that tall the tests are passing?

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

File: workflowproj/operator.go [hunk 1]
```diff
@@ -75,9 +75,9 @@ func GetWorkflowManagedPropertiesConfigMapName(workflow *operatorapi.SonataFlow)
 
 // GetManagedPropertiesFileName gets the default ConfigMap name that holds the managed application property for the given workflow
 func GetManagedPropertiesFileName(workflow *operatorapi.SonataFlow) string {
-	profile := metadata.ProdProfile
+	profile := metadata.QuarkusProdProfile
```
Comment (wmedvede) [inline workflowproj/operator.go:78]: So here we have kind of naming separation, by one side we might be executing the SFW "Preview" profile, but, we create an application-prod.prperties because the quarkus profiling?

Comment (ricardozanini) [reply workflowproj/operator.go:78]: Yes, `prod` is the default Quarkus profiling name: https://quarkus.io/guides/config-reference#default-profiles

Comment (ricardozanini) [reply workflowproj/operator.go:78]: SonataFlow Preview profile uses Quarkus prod profile. We are not mimicking/exposing Quarkus profiles.

Comment (wmedvede) [reply workflowproj/operator.go:78]: yep, I know that "prod" is the default quarkus profile. My question was more related to the fact that when users works with the "Dev" profile, they'll see "application-dev", but, when they work with "Preview" profile, they'll see "application-prod".  Np, but I think this must be clarified in the docs maybe.

**Review by wmedvede — APPROVED** [review]

File: workflowproj/operator.go (hunk 1 above)
Comment (ricardozanini) [reply workflowproj/operator.go:78]: will do thanks!

**Comment by ricardozanini** [comment]
@jakubschwan can you please review? It is a must since it will force other PRs to rebase.
